project_id = "mnfseybrfzexacyzjqwh"

[functions.send-email-verification]
verify_jwt = false

[functions.verify-email]
verify_jwt = false

[functions.send-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false

[functions.delete-account]
verify_jwt = false

[functions.send-pick-notification]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false